hexlet_django_blog/article/urls.py
from django.urls import path
from .views import (
    IndexView,
    ArticleView,
    ArticleFormCreateView,
    ArticleFormEditView,
    ArticleFormDeleteView
)

app_name = 'articles'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:id>/edit/', ArticleFormEditView.as_view(), name='update'),
    path('<int:id>/delete', ArticleFormDeleteView.as_view(), name='delete'),
    path('<int:id>/', ArticleView.as_view(), name='article'),
    path('create/', ArticleFormCreateView.as_view(), name='create'),
]

hexlet_django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from hexlet_django_blog import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    # path('', views.index),
    path('about/', views.AboutView.as_view(), name='about'),
    path('articles/', include('hexlet_django_blog.article.urls')),
    path('admin/', admin.site.urls),
]

hexlet_django_blog/article/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    name = models.CharField(max_length=200)
    body = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

hexlet_django_blog/article/forms.py
from django.forms import ModelForm
from .models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['name', 'body']
        labels = {
            'name': 'Название',
            'body': 'Инфо',
        }

hexlet_django_blog/article/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.http import HttpResponse
from django.views import View

from .models import Article
from .forms import ArticleForm

# Create your views here.


class IndexView(View):

    def get(self, request, *args, **kwargs):
        articles = Article.objects.all()[:15]
        return render(request, 'articles/index.html', context={
                'articles': articles,
            })


class ArticleView(View):

    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Article, id=kwargs['id'])
        return render(request, 'articles/show.html', context={
            'article': article,
        })


class ArticleFormCreateView(View):

    def get(self, request, *args, **kwargs):
        form = ArticleForm()
        return render(request, 'articles/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Статья успешно создана.')
            return redirect('articles:index')
        return render(request, 'articles/create.html', {'form': form})


class ArticleFormEditView(View):

    def get(self, request, *args, **kwargs):
        article_id = kwargs.get('id')
        article = Article.objects.get(id=article_id)
        form = ArticleForm(instance=article)
        return render(request, 'articles/update.html', {
            'form': form, 'article_id': article_id})

    def post(self, request, *args, **kwargs):
        article_id = kwargs.get('id')
        article = Article.objects.get(id=article_id)
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Статья успешно обновлена.')
            return redirect('articles:index')
        return render(request, 'articles/update.html', {
            'form': form, 'article_id': article_id})


class ArticleFormDeleteView(View):

    def post(self, request, *args, **kwargs):
        article_id = kwargs.get('id')
        article = Article.objects.get(id=article_id)
        if article:
            article.delete()
            messages.add_message(request, messages.SUCCESS,
                                 'Статья %s успешно удалена.' % article.name)
        return redirect('articles:index')

# def index(request, tags, article_id):
#     return HttpResponse(f'Статья номер {article_id}. Тег {tags}')

hexlet_django_blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.urls import reverse


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['who'] = 'World'
        return context


class AboutView(TemplateView):
    template_name = 'about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = ['обучение', 'программирование', 'python', 'oop']
        return context


# def index(request):
#     url = reverse(
#         'article',
#         kwargs={'tags': 'python', 'article_id': 42}
#     )
#     return redirect(url)


# def about(request):
#     tags = ['обучение', 'программирование', 'python', 'oop']
#     return render(
#         request,
#         'about.html',
#         context={'tags': tags})

hexlet_django_blog/templates/about.html
{% extends "base.html" %}

{% block title %}Эксперименты с Django на Хекслете{% endblock %}

{% block content %}
    <h1>О блоге</h1>
    <p>Эксперименты с Django на Хекслете</p>
    <p>{{ tags|join:', ' }}</p>
{% endblock %}

hexlet_django_blog/templates/articles/create.html
{% extends "layouts/form.html" %}
{% block url_path %}{% url 'articles:create' %}{% endblock %}
{% block btn_name %}Создать{% endblock %}

hexlet_django_blog/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
    <small>
        <a href="{% url 'articles:create' %}">Создать новую статью</a>
    </small>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <h1>Список статей</h1>
    {% for article in articles %}
        <h2>
            <a href="{% url 'articles:article' article.id %}">{{ article.name }}</a>
        </h2>
        <div>{{ article.body|slice:":200" }}...</div>
        <form action="{% url 'articles:update' article.id %}" method="get">
            <input type="submit" value="Редактировать">
        </form>
        <form action="{% url 'articles:delete' article.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Удалить">
        </form>
    {% endfor %}
{% endblock %}

hexlet_django_blog/templates/articles/show.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ article.name }}</h1>
    <div>{{ article.body }}</div>
{% endblock %}

hexlet_django_blog/templates/articles/update.html
{% extends "layouts/form.html" %}
{% block url_path %}{% url 'articles:update' id=article_id %}{% endblock %}
{% block btn_name %}Сохранить{% endblock %}

hexlet_django_blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Django на Хекслете{% endblock %}</title>
</head>
<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="{% url 'home' %}">Главная</a></li>
            <li><a href="{% url 'articles:index' %}">Статьи</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
        </ul>
        {% endblock %}
    </div>
    <div id="content">
        {% block content %}{% endblock%}
    </div>
</body>
</html>

hexlet_django_blog/templates/index.html
{% extends "base.html" %}

{% block title %}Эксперименты с Django на Хекслете{% endblock %}

{% block content %}
    <h1>Hello, {{ who }}</h1>
{% endblock %}

hexlet_django_blog/templates/layouts/form.html
{% extends 'base.html' %}

{% block content %}
{% if form.subject.errors %}
<div>
    <ul>
        {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ul>
</div>
{% endif %}
<form action="{% block url_path %}{% endblock %}" method="post">
    {% csrf_token %}
    <table border="1">
        {{ form }}
    </table>
    <input type="submit" value="{% block btn_name %}{% endblock %}">
</form>
{% endblock %}